main:
  - name: About
    url: /
    weight: 10
  - name: Publications
    url: /#publications
    weight: 20
  - name: Working Papers
    url: /#working-papers
    weight: 25
  - name: Policy Work
    url: /#policy
    weight: 30
  - name: Presentations
    url: /#presentations
    weight: 40
  - name: Experience
    url: experience/
    weight: 50
  - name: CV
    url: media/CV.pdf
    weight: 60
