main:
  - name: About
    url: /
    weight: 10
  - name: Research
    url: /#research
    weight: 20
  - name: IMF Work
    url: /#imf
    weight: 30
  - name: Presentations
    url: /#presentations
    weight: 40
  - name: Experience
    url: experience/
    weight: 50
  - name: CV
    url: media/CV.pdf
    weight: 60
